# This is a basic workflow to help you get started with Actions

name: Insert Requests from Backstage Details into Postgres Database

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      agent_identifier_name:
        description: 'Agent Name'
        required: true

      components:
        description: 'Components'
        required: true

      agent_action:
        description: 'Agent Action'
        required: true

      duration:
        description: 'Infra life in days'
        required: true

      type:
        description: 'Provisioning request type'
        required: true

      email_id:
        description: 'Email ID of the Requestor'
        required: true

      industry:
        description: 'Industry of the AI Agent'
        required: true

      source_code_needed:
        description: 'Is source code needed'
        required: true

      platform:
        description: 'Hyperscaler Platform'
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  accept_request:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Initialize Variables
        run: |
          echo "Hello"

      - name: Make the HTTP POST request

        
        run: |
          # curl --retry 10 --retry-max-time 180 "http://"${{ secrets.POSTGRES_IP }}"/REQUESTED" -X POST -H "Content-Type: application/json"  -d "{\"id\": \"$(tr -dc a-z0-9 </dev/urandom | head -c 6;echo)\", \"components\": \"${{ github.event.inputs.components }}\", \"requestedtime\": \"$(date --utc --iso-8601=seconds)\" , \"expirytime\": \"$(date --utc --iso-8601=seconds -d "+${{ github.event.inputs.duration }} days")\",\"type\": \"${{ github.event.inputs.type }}\",\"agent_identifier_name\":\"${{ github.event.inputs.agent_identifier_name }}\",\"email_id\":\"${{ github.event.inputs.email_id }}\",\"industry\":\"${{ github.event.inputs.industry }}\",\"source_code_needed\":\"${{ github.event.inputs.source_code_needed }}\",\"platform\":\"${{ github.event.inputs.platform }}\"}"
          curl --retry 10 --retry-max-time 180 "http://"${{ secrets.POSTGRES_IP }}"/REQUESTED" -X POST -H "Content-Type: application/json"  -d @- << EOF
          {
            \"id\": \"$(tr -dc a-z0-9 </dev/urandom | head -c 6;echo)\", 
            \"components\": \"${{ github.event.inputs.components }}\",
            \"requestedtime\": \"$(date --utc --iso-8601=seconds)\" , 
            \"expirytime\": \"$(date --utc --iso-8601=seconds -d "+${{ github.event.inputs.duration }} days")\",
            \"type\": \"${{ github.event.inputs.type }}\",
            \"agent_identifier_name\":\"${{ github.event.inputs.agent_identifier_name }}\",
            \"email_id\":\"${{ github.event.inputs.email_id }}\",
            \"industry\":\"${{ github.event.inputs.industry }}\",
            \"source_code_needed\":\"${{ github.event.inputs.source_code_needed }}\",
            \"platform\":\"${{ github.event.inputs.platform }}\"
          } 
          EOF  
        
      #- name: Debugging Session with Tmate
      #  uses: mxschmitt/action-tmate@v3    
      # Runs a set of commands using the runners shell